import React, { useEffect, useMemo, useState } from 'react';
import {Link, NavLink, Route, Routes} from 'react-router-dom';
function FileCard({children}:{children:React.ReactNode}){return <main className="site-shell">{children}</main>}
function Header({title,fact,intro}:{title:string;fact:string;intro:string}){return <header className="site-header"><div className="site-mark">EH<span> / </span>STUDY LAB</div><div className="site-header-copy"><strong>{title}</strong><span>{fact}</span></div><p>{intro}</p></header>}
function Group({label,heading,children}:{label:string;heading?:boolean;children:React.ReactNode}){return <section className="content-group"><div className="group-label">{label}</div>{children}</section>}
function Closing({children}:{children:React.ReactNode}){return <footer className="site-footer">{children}</footer>}
function useLocalState<T>(key:string,initial:T):[T,(value:T)=>void,{ready:boolean;message:string}]{const [value,setValue]=useState<T>(()=>{try{const stored=localStorage.getItem(key);return stored?JSON.parse(stored):initial}catch{return initial}});function update(v:T){setValue(v);try{localStorage.setItem(key,JSON.stringify(v))}catch{}}return [value,update,{ready:true,message:'Progress is saved on this browser only; it is not synced across devices.'}]}
import data from './content.json';
import networkHero from './figures/network-hero.png';
import fig1 from './figures/figure-1.png'; import fig2 from './figures/figure-2.png'; import fig3 from './figures/figure-3.png';
import fig4 from './figures/figure-4.png'; import fig5 from './figures/figure-5.png'; import fig6 from './figures/figure-6.png';
import fig7 from './figures/figure-7.png'; import fig8 from './figures/figure-8.png'; import fig9 from './figures/figure-9.png';
import './style.css';

type Block = {type:string; text?:string; rows?:string[][]; image?:string};
type Question = {id:string; question:string; answer:string};
const sections = data.sections as {title:string;slug:string;blocks:Block[]}[];
const questions = data.questions as Question[];
const imgs:Record<string,string> = {'figure-1.png':fig1,'figure-2.png':fig2,'figure-3.png':fig3,'figure-4.png':fig4,'figure-5.png':fig5,'figure-6.png':fig6,'figure-7.png':fig7,'figure-8.png':fig8,'figure-9.png':fig9};
const labels = ['Foundations','The lifecycle','Penetration testing','Nmap'];
const category:Record<string,string> = {QH:'Homework',QA:'Rapid fire',QB:'Short answer',QC:'Why questions',QD:'Exam length',QE:'Command lab'};
const phases=['Recon','Scan','Gain access','Maintain','Clear tracks','Report','Retest'];
function ScrollReveal(){useEffect(()=>{const elements=document.querySelectorAll('.reveal'); const o=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('seen');o.unobserve(e.target)}}),{threshold:.08});elements.forEach(e=>o.observe(e));return()=>o.disconnect()},[]);return null}
function Overview(){return <>
  <div className="hero reveal"><div className="hero-copy"><span className="eyebrow">THE STUDY LAB · LECTURES 01-04</span><h1>Learn the system.<br/><em>Then break the question.</em></h1><p>Four complete lectures, 63 active-recall questions, and one last-minute field sheet. Learn it, test yourself, then come back for the parts you missed.</p><div className="hero-actions"><Link to="/lecture-1" className="primary-action">Start studying <span>↗</span></Link><Link to="/quiz" className="secondary-action">Take the quiz <span>↗</span></Link></div></div><div className="radar-art" aria-label="Animated network map"><img className="radar-backdrop" src={networkHero} alt="Custom illustration of connected network nodes"/><div className="radar-grid"/><div className="radar-orbit orbit-one"/><div className="radar-orbit orbit-two"/><div className="radar-sweep"/><i className="node n1"/><i className="node n2"/><i className="node n3"/><i className="node n4"/><span className="radar-center">01 / 04<br/><b>ETHICAL<br/>HACKING</b></span><span className="radar-label top">AUTHORIZATION REQUIRED</span><span className="radar-label bottom">RECON → REPORT</span></div></div>
  <div className="stat-strip reveal"><div><strong>04</strong><span>LECTURES</span></div><div><strong>63</strong><span>QUESTIONS</span></div><div><strong>09</strong><span>ORIGINAL DIAGRAMS</span></div><div><strong>01</strong><span>NIGHT-BEFORE SHEET</span></div></div>
  <Group label="Course map" heading><p className="section-intro">The entire guide, not a condensed excerpt. Pick up where you need the most work.</p><div className="course-grid">{sections.slice(0,4).map((s,i)=><Link to={'/'+s.slug} className="course-card reveal" key={s.slug}><span className="course-index">0{i+1} / LECTURE</span><div className={'course-icon icon-'+i} aria-hidden="true">{['◎','↗','◇','⌘'][i]}</div><h2>{labels[i]}</h2><p>{['Hackers, ethics, the CIA triad, Kali Linux.','Seven phases, reconnaissance, scanning, Nikto.','Box types, zero-days, Dmitry, the rules of engagement.','Ports, handshakes, scan states, commands.'][i]}</p><span className="course-bottom">Open lecture <b>↗</b></span></Link>)}</div></Group>
  <div className="lifecycle reveal"><span className="eyebrow">ONE MAP TO KEEP IN YOUR HEAD</span><h2>The seven-phase lifecycle</h2><div className="phase-track">{phases.map((p,i)=><div className="phase" key={p}><b>{String(i+1).padStart(2,'0')}</b><span>{p}</span></div>)}</div><p>The first five phases model an intrusion. The last two turn a test into useful security work.</p></div>
  <div className="feature-grid"><Link to="/quiz" className="feature feature-dark reveal"><small>ACTIVE RECALL / 63 QUESTIONS</small><h2>Know it, or just recognise it?</h2><p>Reveal the model answer only after you have said yours. Mark it, filter by question type, and revisit missed prompts.</p><b>Enter quiz →</b></Link><Link to="/night" className="feature feature-amber reveal"><small>THE FINAL REVIEW</small><h2>The night-before page.</h2><p>Thirty-plus compact lines, from permission and intent to Nmap flags. Designed for the last hour.</p><b>Open field sheet →</b></Link></div>
  <p className="safety-note">Lab commands in the guide are examples to understand, not instructions to scan third-party hosts. Only test systems you own or have written permission to assess.</p>
</>}
function Lecture({index}:{index:number}) {const section=sections[index];const [outline,setOutline]=useState(false);const heads=section.blocks.filter(b=>b.type==='p'&&/^\d\.\d+\s/.test(b.text||''));let fig=0;return <>
  <div className="chapter-hero"><span className="eyebrow">{index===4?'THE NIGHT-BEFORE PAGE':`LECTURE ${String(index+1).padStart(2,'0')} / 04`}</span><h1>{index===4?'The field sheet':labels[index]}</h1><p>{index===4?'Thirty-two fast facts and the final exam note, drawn from the study guide.':['How hacking became a profession, and why authorization changes everything.','Map the attack from reconnaissance to retesting.','Prove impact within scope and report what matters.','Understand the network before you read the scan.'][index]}</p><div className="chapter-tools"><button onClick={()=>setOutline(!outline)}>{outline?'Hide':'Show'} outline <span>⌄</span></button><Link to="/quiz">Practice questions ↗</Link></div></div>
  {outline&&<div className="outline"><b>IN THIS LECTURE</b>{heads.map(h=><button key={h.text} onClick={()=>document.getElementById(slug(h.text||''))?.scrollIntoView({behavior:'smooth',block:'start'})}>{h.text}</button>)}</div>}
  <div className="chapter-content">{section.blocks.map((b,i)=>{
    const t=b.text||'';
    if(b.type==='figure'){fig++;return <figure className="source-figure" key={i}><img src={imgs[b.image||'']} alt={'Original diagram '+fig+' from lecture '+(index+1)}/><figcaption>FIGURE {String(fig).padStart(2,'0')} · FROM THE STUDY GUIDE</figcaption></figure>}
    if(b.type==='table')return <div className="table-scroll" key={i}><table><thead><tr>{b.rows?.[0].map((c,j)=><th key={j}>{c}</th>)}</tr></thead><tbody>{b.rows?.slice(1).map((r,j)=><tr key={j}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>)}</tbody></table></div>;
    if(/^\d\.\d+\s/.test(t))return <h2 id={slug(t)} className="lesson-heading" key={i}><span>{t.match(/^\d\.\d+/)?.[0]}</span>{t.replace(/^\d\.\d+\s*/,'')}</h2>;
    if(/^MEMORY HOOK\./.test(t)||/^TRUE STORY\./.test(t)||/^EXAM ALERT\./.test(t))return <aside className={'study-callout '+(t.startsWith('TRUE')?'story':t.startsWith('EXAM')?'alert':'memory')} key={i}><b>{t.split('.')[0]}</b><p>{t.slice(t.indexOf('.')+1).trim()}</p></aside>;
    if(/^\d+\.\s/.test(t)&&index===4)return <div className="night-line" key={i}><span>{t.match(/^\d+/)?.[0]}</span><p>{t.replace(/^\d+\.\s*/,'')}</p></div>;
    if(/^(Black-hat|White-hat|Gray-hat|Script kiddies|Hacktivists|State-sponsored|Cybercriminals|Legality\.|Confidentiality\.|Integrity\.|Non-malfeasance\.|Responsibility\.|Transparency\.|Professionalism\.)/.test(t))return <p className="definition" key={i}>{t}</p>;
    if(t.length<155&&i>0&&section.blocks[i-1]?.type==='figure')return <p className="figure-context" key={i}>{t}</p>;
    return <p className="lesson-paragraph" key={i}>{t}</p>
  })}</div><div className="next-step"><span>KEEP MOVING</span><h2>{index===3?'Can you explain it without looking?':index===4?'Test what stuck.':'Next: '+labels[index+1]}</h2><Link to={index===3||index===4?'/quiz':'/lecture-'+(index+2)}>Continue ↗</Link></div>
</>}
function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function Quiz(){const [filter,setFilter]=useState('ALL'); const [index,setIndex]=useState(0); const [show,setShow]=useState(false);const [mode,setMode]=useState<'all'|'missed'>('all');const [results,setResults,saved]=useLocalState<Record<string,'got'|'missed'>>('ethical-lab-results.v1',{});const list=useMemo(()=>questions.filter(q=>(filter==='ALL'||q.id.startsWith(filter))&&(mode==='all'||results[q.id]==='missed')),[filter,mode,results]);const q=list[Math.min(index,list.length-1)];const answered=Object.keys(results).length;function pickFilter(v:string){setFilter(v);setIndex(0);setShow(false)}function next(){setShow(false);setIndex(i=>(i+1)%Math.max(1,list.length))}function grade(mark:'got'|'missed'){if(saved.ready)setResults({...results,[q.id]:mark});next()}
return <><div className="chapter-hero quiz-head"><span className="eyebrow">ACTIVE RECALL / 63 SOURCE QUESTIONS</span><h1>Test your recall.</h1><p>Say the answer aloud before revealing it. The model answers come directly from the guide.</p><div className="quiz-stats"><span><b>{answered}</b> tried</span><span><b>{Object.values(results).filter(v=>v==='got').length}</b> got it</span><span><b>{Object.values(results).filter(v=>v==='missed').length}</b> revisit</span></div></div>
<div className="quiz-toolbar"><div className="filter-row" aria-label="Question type">{['ALL','QH','QA','QB','QC','QD','QE'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>pickFilter(f)}>{f==='ALL'?'All':category[f]}</button>)}</div><div className="mode-row"><button onClick={()=>{setMode('all');setIndex(0);setShow(false)}} className={mode==='all'?'selected':''}>All questions</button><button onClick={()=>{setMode('missed');setIndex(0);setShow(false)}} className={mode==='missed'?'selected':''}>Missed only</button></div></div>
{q?<div className="quiz-card" key={q.id}><div className="quiz-meta"><span>{category[q.id.slice(0,2)]} · {q.id}</span><span>{Math.min(index,list.length-1)+1} / {list.length}</span></div><div className="quiz-progress"><i style={{width:`${((Math.min(index,list.length-1)+1)/list.length)*100}%`}}/></div><h2>{q.question}</h2>{!show?<div className="answer-prompt"><span>THINK FIRST. SAY IT OUT LOUD.</span><button className="primary-action" onClick={()=>setShow(true)}>Reveal answer ↓</button></div>:<div className="answer-reveal"><span>MODEL ANSWER</span>{q.answer.split('\n\n').map((p,i)=><p key={i}>{p}</p>)}{q.id==='QH1'&&<figure className="source-figure"><img src={fig9} alt="Original nesting diagram showing network security inside cyber security inside information security"/><figcaption>ORIGINAL STUDY GUIDE DIAGRAM</figcaption></figure>}<div className="grade-row"><button onClick={()=>grade('missed')}>↺ Need another look</button><button onClick={()=>grade('got')}>✓ Got it</button></div></div>}<div className="quiz-footer"><button onClick={()=>{setShow(false);setIndex(i=>(i-1+list.length)%list.length)}}>← Previous</button><button onClick={next}>Skip / next →</button></div></div>:<div className="empty-state"><h2>No missed questions in this set.</h2><p>Mark a question "Need another look" to collect it here.</p><button onClick={()=>setMode('all')}>Show all questions</button></div>}
<p className="quiz-save">{saved.message || 'Progress is local to this browser and is not synced across devices.'}</p></>}
export function App(){return <FileCard><ScrollReveal/><Header title="Ethical Hacking: Study Lab" fact="MAKAUT · M.Tech Information Security · Lectures 1-4" intro="Study the complete guide, then test yourself with all 63 source questions."/><nav className="file-nav" aria-label="Study navigation"><NavLink to="/" end>Overview</NavLink>{sections.slice(0,4).map((s,i)=><NavLink key={s.slug} to={'/'+s.slug}>0{i+1}</NavLink>)}<NavLink to="/quiz">Quiz</NavLink><NavLink to="/night">Night before</NavLink></nav><Routes><Route path="/" element={<Overview/>}/>{sections.slice(0,4).map((s,i)=><Route key={s.slug} path={'/'+s.slug} element={<Lecture index={i}/>}/>)}<Route path="/quiz" element={<Quiz/>}/><Route path="/night" element={<Lecture index={4}/>}/></Routes><Closing>Adapted from the supplied Ethical Hacking study guide, Lectures 1-4. For authorized study and testing only.</Closing></FileCard>}
